# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-04 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msrh_user', '0014_pending_trainings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_trainings',
            name='emp_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
