# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-04 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msrh_user', '0016_auto_20170705_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Names',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='pending_trainings',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msrh_user.DEPARTMENT'),
        ),
        migrations.AlterField(
            model_name='pending_trainings',
            name='emp_list',
            field=models.ManyToManyField(blank=True, null=True, to='msrh_user.EMPLOYEE'),
        ),
        migrations.AlterField(
            model_name='pending_trainings',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='msrh_user.Training'),
        ),
    ]
