# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-04 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msrh_user', '0013_auto_20170702_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending_Trainings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_count', models.IntegerField(blank=True, max_length=10, null=True)),
                ('dept', models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='msrh_user.DEPARTMENT')),
                ('emp_list', models.ManyToManyField(to='msrh_user.EMPLOYEE')),
                ('name', models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='msrh_user.Training')),
            ],
        ),
    ]
