# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-11 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msrh_user', '0020_auto_20170705_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='trainings',
            field=models.ManyToManyField(blank=True, null=True, to='msrh_user.Training'),
        ),
        migrations.AlterField(
            model_name='pending_trainings',
            name='emp_list',
            field=models.ManyToManyField(blank=True, null=True, to='msrh_user.Names'),
        ),
    ]
